### ISSUE TITLE
Improve README and Wiki Documentation

### ISSUE THREAD

**Issue by sebeard** [sebeard/iorek#23]
### Outline
_As a developer_
_I want a broad simple README while maintaining documentation elsewhere_
_So that I can refer to richer documentation if I need to_

The documentation for Iorek is currently stored in a singular place and is pretty verbose. Consolidate down and add information to wiki pages; while maintaining a single reference point for the documentation provided.

### Tasks:
**Add Wiki Pages**
- [ ] Features (with sub pages for configuration)
- [ ] Contributing
- [ ] Sponsorship

**Update README**
- [ ] Point to Wiki Pages
- [ ] Update Etymology Section
- [ ] Add Links to PwnedPasswords
- [ ] Add Sponsorship
- [ ] Add Contributing Link

**Fix spelling errors**
- [ ] `compromised.password.**service**` determines which integration to use. **Defaults** automatically to "pwnedpassword" if not supplied.
- [ ] `compromised.password.pwnedpasswords.prefix.length` This is the required prefix length of the SHA-1 Hash provided to the Pwned Passwords API for **k-anonymity**.
