### ISSUE TITLE
Prevent Usernames being used in Password

### ISSUE THREAD

**Issue by sebeard** [sebeard/iorek#25]
### Outline

_As Security Engineer_
_I want to prevent the users of the system from using their username as part of their password_
_So that the passwords being used are more secure_

### Tasks
- [ ] Add new constraint
- [ ] Add new validator
- [ ] Add to Sample
- [ ] Functional Test
